<?php defined('SYSPATH') OR die('No direct access allowed.');

return array
(
	'tinyint'           => array('type' => 'int', 'max' => 127),
	'smallint'          => array('type' => 'int', 'max' => 32767),
	'mediumint'         => array('type' => 'int', 'max' => 8388607),
	'int'               => array('type' => 'int', 'max' => 2147483647),
	'integer'           => array('type' => 'int', 'max' => 2147483647),
	'bigint'            => array('type' => 'int', 'max' => 9223372036854775807),
	'float'             => array('type' => 'float'),
	'double'            => array('type' => 'float'),
	'double unsigned'   => array('type' => 'float'),
	'decimal'           => array('type' => 'float'),
	'real'              => array('type' => 'float'),
	'numeric'           => array('type' => 'float'),
	'float unsigned'    => array('type' => 'float', 'min' => 0),
	'boolean'           => array('type' => 'boolean'),
	'bit'               => array('type' => 'boolean'),
	'time'              => array('type' => 'string', 'format' => '00:00:00'),
	'date'              => array('type' => 'string', 'format' => '0000-00-00'),
	'year'              => array('type' => 'string', 'format' => '0000'),
	'datetime'          => array('type' => 'string', 'format' => '0000-00-00 00:00:00'),
	'timestamp'         => array('type' => 'string', 'format' => '0000-00-00 00:00:00'),
	'char'              => array('type' => 'string', 'exact' => TRUE),
	'binary'            => array('type' => 'string', 'binary' => TRUE, 'exact' => TRUE),
	'varchar'           => array('type' => 'string'),
	'enum'              => array('type' => 'string'),
	'set'               => array('type' => 'string'),
	'varbinary'         => array('type' => 'string', 'binary' => TRUE),
	'blob'              => array('type' => 'string', 'binary' => TRUE),
	'tinyblob'          => array('type' => 'string', 'binary' => TRUE),
	'mediumblob'        => array('type' => 'string', 'binary' => TRUE),
	'longblob'          => array('type' => 'string', 'binary' => TRUE),
	'clob'              => array('type' => 'string', 'binary' => TRUE),
	'text'              => array('type' => 'string'),
	'tinytext'          => array('type' => 'string'),
	'mediumtext'        => array('type' => 'string'),
	'longtext'          => array('type' => 'string'),
);
